version: "3.8"

services:
  jenkins:
    networks:
      - jenkins
    container_name: jenkins-latest
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home

networks:
  jenkins:
